### PR TITLE
Add OSX compatibility and remark about new TeX Live

### PR DESCRIPTION
**Pull request by lahnerml**

### CODE REVIEW

**Comment by valentjn** [comment]
Thanks for the PR. That TeX Live issue intrigues me, since that's kind of important.

I remember having tried upgrading once a few months ago (I'm still using 2017), but everything started to break down after that, so I quickly regretted that decision and downgraded again. I'm not sure about the actual errors I got, though.

If we knew what component of the template causes the incompatibility, then we could probably disable it. Otherwise I'm fine with a warning in the caveat section, as I don't have too much time on my hands to debug it properly.

**Comment by valentjn** [comment]
BTW, the correct place to report/discuss bugs is the issues tab above, not PRs. I've just tried the template with a fresh Ubuntu 18.04 LTS and manual TeX Live 2018 installation, and it doesn't compile for me either, but I'm getting a different error, see issue #3. (Sounds like the TeX Live guys messed up this release.) If this doesn't match the bug you experience, then please open another issue.

GitHub doesn't seem to support merging of some of the commits (cherry-picking). I'd like to accept
e174159, rewrite df8d9a2 (to match #3), and decline 95b859e (isn't consistent across all files and will lead to many merge conflicts for me). Guess I'll have to do that manually.

**Comment by lahnerml** [comment]
As you correctly stated in #3 the issue cannot be fixed in this code. Thus, the template failing to compile with TeXLive in version 2018 is nothing that can be fixed here.

**Comment by valentjn** [comment]
Ah ok, I get it now. Yeah, correct. Still, having a proper issue with problem description doesn't hurt. (And of course I meant issue #3, not #2 (this PR). I'm used to GitLab, which numbers issues continuously... I'm still getting the hang of GitHub :wink:)

**Comment by lahnerml** [comment]
I will split this pull request later. Thus, I will close it for now.

**Pull request closed without merging**
